# Generated by Django 4.2.4 on 2023-11-24 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_deMadera', '0002_desk_leg_delete_articulos_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_articulo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_deMadera.leg')),
                ('cubierta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_deMadera.desk')),
            ],
        ),
    ]
